### ISSUE TITLE
Allow players to have multiple islands

### ISSUE THREAD

**Issue by dresnite** [dresnite/SkyBlock#183]

**Comment by benda95280** [comment]
Any news on this feature ? If they can ahve multiples islands and, why not, differents types of islands, it would be amazing !

Thanks

**Comment by andresbytes** [comment]
This feature would take quite a lot of time to be developed, and I'm afraid that currently I don't have much time for OSS contributions. However, this project will always welcome external contributions, feel free to open a PR if you want this feature implemented.
