### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [dresnite/SkyBlock#226]
• Custom island in-game like RedSkyBlock 
• World name is the name of the player who owns the island
• If the player deletes the world island it will be deleted the folder world 
• In config There is a check player if he is an android device it will open the island menu Form, if he is not an android he will open the GUI menu

**Comment by Endermanbugzjfc** [comment]
> • Custom island in-game like RedSkyBlock 
> 
> • World name is the name of the player who owns the island
> 
> • If the player deletes the world island it will be deleted the folder world 
> 
> • In config There is a check player if he is an android device it will open the island menu Form, if he is not an android he will open the GUI menu

Consider making custom islands with this plugin!

https://github.com/crnw-dev/IslandArchitect
