### ISSUE TITLE
No items in the trunk

### ISSUE THREAD

**Issue by LaChere9offi** [dresnite/SkyBlock#229]
Good morning 

I put the latest version available on poggit. 
When I create an island the trunk of the island is empty. 

I asked a lot of people they have the same problem on their server. 

Can you help me 

Thank you

**Comment by ElectroGamesYT** [comment]
What trunk?

**Comment by EmKuphi** [comment]
Il faut modifier la protection du spawn sur ton fichier server.proporties je crois
