### ISSUE TITLE
No items in chest

### ISSUE THREAD

**Issue by MidWolfhunter** [dresnite/SkyBlock#235]
I am unable to configure config to add items in the chest.  I've asked a dev about this and he said it could be a bug because the config seems right. Please fix this and perhaps make the config a little more clear.

**Comment by llPushkarSinghll** [comment]
> I am unable to configure config to add items in the chest. I've asked a dev about this and he said it could be a bug because the config seems right. Please fix this and perhaps make the config a little more clear.

Do spawn protection off in server.properties
