### ISSUE TITLE
Generator not found

### ISSUE THREAD

**Issue by AraaCuteUwU** [dresnite/SkyBlock#251]
Shelly generator not found when i try to create an island (/is create)

**Comment by UnknownNull** [comment]
@xxFLORII

**Comment by UnknownNull** [comment]
This not crash.
Error message in game

**Comment by UnknownNull** [comment]
Error: Shelly generator not found when i try to create an island

**Comment by xxFLORII** [comment]
ah okay, i will see what i can do.

**Comment by xxFLORII** [comment]
can you try to use `/is create shelly`?

**Comment by UnknownNull** [comment]
> can you try to use `/is create shelly`?

Yes but nothing...

**Comment by xxFLORII** [comment]
https://github.com/BlckqPlugins/SkyBlock

can you try this version?

**Comment by AraaCuteUwU** [comment]
> https://github.com/BlckqPlugins/SkyBlock
> 
> can you try this version?

Still can't create island

**Comment by xxFLORII** [comment]
![441F480B-D0E4-40DD-A1DE-D0BAAC059443](https://user-images.githubusercontent.com/38558911/188310172-23aa5bae-e450-47b5-ad78-348034a0f5c6.png)

it‘s working ( thanks to Justin for testing )

**Comment by UnknownNull** [comment]
> ![441F480B-D0E4-40DD-A1DE-D0BAAC059443](https://user-images.githubusercontent.com/38558911/188310172-23aa5bae-e450-47b5-ad78-348034a0f5c6.png)
> 
> it‘s working ( thanks to Justin for testing )

chest island not openend...

**Comment by xxFLORII** [comment]
okay, i will fix it today/tomorrow

**Comment by UnknownNull** [comment]
> okay, i will fix it today/tomorrow

nice...

**Comment by xxFLORII** [comment]
fixed in the latest commit

**Comment by UnknownNull** [comment]
> fixed in the latest commit

can not create island ... error in game
and bug cmd visit and tp ....

 [Server thread/CRITICAL]: Error: "Value of type bool is not callable" (EXCEPTION) in "plugins/SkyBlock-pm4/src/room17/SkyBlock/command/presets/VisitCommand" at line 60

**Comment by xxFLORII** [comment]
thank you, i will fix it as soon as i am at home :)

**Comment by UnknownNull** [comment]
> thank you, i will fix it as soon as i am at home :)

Thank you bro

**Comment by xxFLORII** [comment]
should be fixed in latest commit

**Comment by dresnite** [comment]
Closed by @xxFLORII
